# [START cloudrun_rails_cloudbuild]
steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ["-c", "docker build --build-arg RAILS_MASTER_KEY=$$RAILS_KEY -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} . "]
    secretEnv: ["RAILS_KEY"]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
    - -c
    - |
      gcloud run deploy ${_SERVICE_NAME} --image gcr.io/${PROJECT_ID}/${_SERVICE_NAME} \
      --update-env-vars=RAILS_MASTER_KEY=$$RAILS_KEY \
      --update-env-vars=DB_HOST=$$DB_HOST \
      --update-env-vars=DB_PORT=$$DB_PORT \
      --update-env-vars=DB_NAME=$$DB_NAME \
      --update-env-vars=DB_USER=$$DB_USER \
      --update-env-vars=DB_PASS=$$DB_PASS \
      --region asia-northeast1 \
      --allow-unauthenticated
    secretEnv: ["RAILS_KEY", "DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASS"]

substitutions:
  _SERVICE_NAME: rails-cloud-run
  _SECRET_NAME: RAILS_KEY

availableSecrets:
  secretManager:
  - versionName: projects/156178245176/secrets/${_SECRET_NAME}/versions/latest
    env: RAILS_KEY

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"

options:
  logging: CLOUD_LOGGING_ONLY
# [END cloudrun_rails_cloudbuild]
